tasks:
  - init: npm i -g pnpm && pnpm i
    command: pnpm dev

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
    - bradlc.vscode-tailwindcss@0.4.3:OmgUwJW/nFom0SHcYT4VnQ==
    - octref.vetur@0.26.1:NrU4ZTLY6IF/1G6B/QLuIQ==