[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200