name: Deploy Website

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: node_modules/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Build Production
        run: npx pnpm i --store=node_modules/.pnpm-store && npm run build

  deploy-netlify:
    needs: test
    if: github.event_name == 'push'
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: node_modules/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      
      - name: Build Production
        env:
          FUNCTIONS_ENDPOINT: https://ovaashumanpose-test.azurewebsites.net/api
        run: npx pnpm i --store=node_modules/.pnpm-store && npm run build

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod

  deploy-azure-static-web:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy to Azure Static Web App
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        env:
          FUNCTIONS_ENDPOINT: https://ovaas-backend.azurewebsites.net/api
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_ROCK_03BB9DD00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"
          app_build_command: "npx pnpm i --store=node_modules/.pnpm-store && npm run build"

  screenshot:
    needs: deploy-netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://ovaas-front.netlify.app
          destination: screenshot.png
          full-page: true
      - name: Download screenshot from last step
        uses: actions/download-artifact@v1
        with:
          name: screenshot
      - name: Commit to Github
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: website screenshot"
