name: Screenshot

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://ovaas-front.netlify.app
          destination: screenshot.png
          full-page: true
      - name: Download screenshot from last step
        uses: actions/download-artifact@v1
        with:
          name: screenshot
      - name: Commit to Github
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: website screenshot"
